// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingCalcController from "./booking_calc_controller"
import DismissableController from "./dismissable_controller"
import DropdownController from "./dropdown_controller"
import MobileMenuController from "./mobile_menu_controller"
import PaymentFormController from "./payment_form_controller"
import PropertyMapController from "./property_map_controller"
import SidebarController from "./sidebar_controller"
application.register("booking-calc", BookingCalcController)
application.register("dismissable", DismissableController)
application.register("dropdown", DropdownController)
application.register("mobile-menu", MobileMenuController)
application.register("payment-form", PaymentFormController)
application.register("property-map", PropertyMapController)
application.register("sidebar", SidebarController)
